name: Workflow Validation

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: write
  id-token: write

jobs:
  validate-workflows:
    name: Validate GitHub Actions Workflows
    uses: zavestudios/platform-pipelines/.github/workflows/workflow-ci.yml@95dc3be12e3915599f3f1b99c75864d4c8742c7e
